### ISSUE TITLE
The section of code for generating the tuning sample and the -1.48 parameter were not found

### ISSUE THREAD

**Issue by cust-lh** [IntelligentSystemsLab/ST-EVCDP#1]
Hello,

I am currently working with the PAG model for electric vehicle (EV) charging demand prediction, as described in your recent paper titled "A physics-informed and attention-based graph learning approach for regional electric vehicle charging demand prediction" (arXiv:2309.05259v1). First of all, thank you for your significant contribution to this field.

I have downloaded the associated code from and have been exploring its implementation. However, I am facing some challenges in identifying the specific parts of the code that correspond to the meta-learning strategy, particularly the Physics-Informed Meta-Learning (PIML) aspect you mentioned in the paper.

In the paper, you describe an innovative approach combining Physics-Informed Meta-Learning with Graph Attentional Network (GAT) and Temporal Pattern Attention (TPA) for model pre-training. However, upon reviewing the provided code, it's not immediately clear how this meta-learning strategy is implemented, especially regarding the generation of tuning samples based on physical or economic laws, and their use in the pre-training phase.

Could you please provide some guidance on where to find this implementation in the code, or offer any additional insights on how the meta-learning process is integrated into the model training? Any additional documentation or examples would also be greatly appreciated.

Thank you for your time and assistance. I am looking forward to your response and to further exploring this innovative approach.

Best regards,
Aaron Liu

**Comment by Quhaoh233** [comment]
Thanks so much for your contributions to this issue. 

First, we have updated the code: the physics-informed meta-learning process was packaged at learner.py. Second, the tuning samples can be found in Dataset modules, while the parameter -1.48 can be found in the 'law_list' in main.py.

If any issues, please let us know!

**Comment by Quhaoh233** [comment]
Note that, the parameter does not have to be -1.48, it can be manually defined. In the case of our paper, it just has to be negative.
