### ISSUE TITLE
Ask questions about data sets

### ISSUE THREAD

**Issue by cust-lh** [IntelligentSystemsLab/ST-EVCDP#2]
I need to obtain a dataset spanning more than one year. Could you please recommend this open-source applications or share any suggestions on how to acquire such data? Your help is greatly appreciated. Thank you!

**Comment by Quhaoh233** [comment]
Thank you for your interest and sorry for the late response. After rigorous validation, we are excited to announce the release of the early access version of ST-EVCDP-v2, which covers a timeframe of one year, spanning from September 2022 to September 2023. You can download the data from Google Drive Link: https://drive.google.com/drive/folders/1sqOUEpMh8VMiJhrT-MOn5OsB1-KirUVq?usp=drive_link.
